version: 1.1.x.{build}
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
  - SET
  - 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
  - 'mkdir C:\tmp && exit 0'
  - 'curl -o C:\tmp\pdk-latest.msi -L "https://pm.puppet.com/cgi-bin/pdk_download.cgi?dist=win&arch=x64&ver=latest"'
  - 'msiexec.exe /i C:\tmp\pdk-latest.msi AGREETOLICENSE="yes" /qn /l*v "C:\tmp\pdk-install.log"'
environment:
  matrix:
    -
      CHECK: 'validate'
    -
      CHECK: 'test unit'
matrix:
  fast_finish: true
build: off
test_script:
  - ps: |
      pdk --version
      pdk -h
  - powershell -Command "pdk %CHECK% --debug; if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }"
notifications:
  - provider: Email
    to:
      - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
